#!/bin/sh

# Manually run the unix maintenance scripts
sudo periodic daily weekly monthly

# Run OSX update
sudo softwareupdate -i -a

# Homebrew
brew update
brew upgrade --all
brew cleanup
brew cask cleanup
brew doctor

# Apps that require manual poining and clicking
open /Applications/Utilities/Disk\ Utility.app
open /Applications/App\ Store.app
open /Applications/CleanMyMac\ 2.app

