#!/bin/sh

# Manually run the unix maintenance scripts
sudo periodic daily weekly monthly

# Run OSX update
sudo softwareupdate -i -a --restart

# Homebrew
brew update
brew upgrade
brew cleanup
brew doctor

# Apps that require manual poining and clicking
open /System/Applications/Utilities/Disk\ Utility.app
open /System/Applications/App\ Store.app
open /Applications/CleanMyMac\ X.app
